{% set name = "pybinding" %}
{% set version = "0.9.2" %}
{% set sha256 = "8211c6843ff8fd493de2168337e363a6888d0294e0e96a4b0995578227a83df1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: True  # [py<35]
  number: 0

requirements:
  build:
    - python
    - setuptools
    - toolchain
    - cmake
  run:
    - python
    - numpy >=1.12
    - scipy >=0.19
    - matplotlib >=2.0
    - pytest >=3.0

test:
  imports:
    - pybinding

about:
  home: http://pybinding.site/
  license: BSD 2-Clause
  license_family: BSD
  license_file: license.md
  summary: 'Package for numerical tight-binding calculations in solid state physics'
  doc_url: http://docs.pybinding.site/
  dev_url: https://github.com/dean0x7d/pybinding

extra:
  recipe-maintainers:
    - dean0x7d
