travis:
  secure:
    BINSTAR_TOKEN: RRpzueBfzas2i0ZfScRi74xV723nFE62jYj71lfENh6zNI9yME83Q8M32yjxmqU8HgfJw6WHYqaWnZ4bixeuNS8BZS4IbrXWbhi3q/5+O2ZIAUz9sxv2p/JcpQb4FfRe4+bDRcmMi21h4pU+5R2XnX84xUDWxunJr4Hpc024f/ar348FpIDRg5rnLonQasxRIi8nqcdTsEXIJU1nTZ1NpKH8mHsSjIEjUElPJF+Mwj4zAW6YXzlqCyTjlDZaZGfMUz7KBLRTPV642NaCDmWu73zA6thWC4QZ5DcFNANqdZTxnvBlxZU7Uf4GMbHizhPH9GZ4YcXO1mwVe2bGSZINuKqncLFuIco+wz9p76+K8UxOBFMY4NmO0/J7ItakeS8knaPENVWrT0ItVtQmzY599mTHsRBCMpPk5cNb9TFH77iXQt5A4n1Vk+bUsrTJVUR1U+hsRbb8RaCcctFcPY8NHyQy3xH3DkCdXuDNqEs+DPC7RYokvIRgYWhvRkADqn+91YuDVfVWIfgEkkRc2Qwc5/1ZCLT0RhoanfgyymMvqF7d5O17C7fDifZmnPzZ2skBdPx8zG+sSdDC2Kp5SPMyrUlzmJor28FiXF1RQ/XPaXAt0/BRqwUjVGYxGahXivghvDPnBerIixs5LkQaj5i9EPs8aqwYVpdrNBNi8ybLVmY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
